#!/bin/bash
# ~~~~~~~~~~~~~~
# compiling goby
# ~~~~~~~~~~~~~~
#
# satisfy the third party dependencies in DEPENDENCIES:
# > ./DEPENDENCIES
# run cmake to configure and generate Makefiles
# > ./CONFIGURE
# then, to install locally (goby/bin, goby/include, goby/lib
# > ./INSTALL
# to install to system
# > sudo ./INSTALL

pushd build
cmake .. $@
popd
