#!/bin/bash
# ~~~~~~~~~~~~~~~~~~~~~~~~
# third-party dependencies
# ~~~~~~~~~~~~~~~~~~~~~~~~

# these are given as debian/ubuntu package names.
# to install in these distributions use (as root or with
# sudo):
# > apt-get install {packagename}

# most other distributions will have the appropriate
# package as well; it's up to you to find out what it is

# global:
sudo apt-get install \
     libboost-dev # (1.34 or newer)

# libdccl:
sudo apt-get install \
     libxerces-c-dev # (or libxerces-c2-dev)

# libmmdriver:
sudo apt-get install \
     libasio-dev \
     libboost-date-time-dev
