#!/bin/bash
set -e -u
# ~~~~~~~~~~~~~~~~~~~~~~~
# third-party dependencies
# ~~~~~~~~~~~~~~~~~~~~~~~~

# most other distributions will have the appropriate
# package as well; it's up to you to find out what it is.
# if you don't know what a package is or does,
# search for it on http://packages.ubuntu.com/
# and you should be able to find the analog for your system
# if that fails, you can always download and compile from source
#
# if you need to compile boost from source, I recommend
# the boost-cmake distribution rather than the official
# bjam distribution. See https://svn.boost.org/trac/boost/wiki/CMake

# build-essential: gcc, c++ library, etc.
# cmake: Cross Platform Make: http://www.cmake.org/
# boost: header-only libraries in boost: http://www.boost.org/
# boost-*: compiled libraries in boost: http://www.boost.org
# xerces: Apache XML parser: http://xerces.apache.org/xerces-c/
# crypto++: Cryptography: http://www.cryptopp.com/
# protobuf: Google Protocol Buffers: http://code.google.com/p/protobuf/
# wt*: Web Toolkit: http://www.webtoolkit.eu/wt
#   packages are provided on Ubuntu 10.10 (maverick) only, 
#   others will have to download Wt and compile from source:
#   http://www.webtoolkit.eu/wt#/download

if [[ $UID -ne 0 ]]; then
    printf "You must run this script as root. Use 'sudo' in Ubuntu. \n" 1>&2
    exit 1
fi


red="\33[1;31m"
nc="\33[1;0m"
green="\33[1;32m"

ubuntu_base_packages=\
"build-essential 
cmake"

ubuntu_boost_packages=\
"libboost-dev
libboost-system-dev
libboost-date-time-dev
libboost-thread-dev
libboost-regex-dev
libboost-program-options-dev
libboost-signals-dev
libboost-filesystem-dev"

ubuntu_xerces_package=\
"libxerces-c-dev"

ubuntu_other_packages=\
"libcrypto++-dev
libncurses-dev
libprotobuf-dev"

ubuntu_wt_packages=\
"libwt-dev
libwtdbo-dev
libwtdbosqlite-dev"

if [ -e "`which aptitude`" ]; then
    if [[ ! `aptitude search ${ubuntu_wt_packages}` ]]; then
        echo "adding ppa:pgquiles/wt for Wt packages"
        add-apt-repository ppa:pgquiles/wt
	aptitude update
    fi 

    if [[ ! `aptitude search ${ubuntu_xerces_package}` ]]; then
        ubuntu_xerces_package="libxerces-c2-dev"
    fi 
    
    aptitude -y install $ubuntu_base_packages || printf $red"Could not install base packages\n"$nc
    aptitude -y install $ubuntu_boost_packages || printf $red"Could not install boost packages: see http://www.boost.org/\n"$nc
    aptitude -y install $ubuntu_xerces_package || printf $red"Could not install xerces package\n"$nc
    aptitude -y install $ubuntu_other_packages || printf $red"Could not install some packages: read the top of this file (DEPENDENCIES)\n"$nc
    aptitude -y install $ubuntu_wt_packages || printf $red"Could not install Wt packages: you need to download from source. See http://www.webtoolkit.eu/wt#/download\n"$nc
fi


#redhat_packages=\
#""
