#!/bin/bash
# ~~~~~~~~~~~~~~
# compiling goby
# ~~~~~~~~~~~~~~
#
# satisfy the third party dependencies in DEPENDENCIES:
# > ./DEPENDENCIES
# then, to install locally (goby/bin, goby/include, goby/lib
# > ./INSTALL
# to install to system
# > sudo ./INSTALL

pushd build
cmake ..

if [[ $UID -ne 0 ]]; then
    # if user is not root, build to goby/bin, goby/include, and goby/lib:
    make $@
else
    # otherwise install to /usr/local/bin, /usr/local/lib, /usr/local/include
    make install $@
fi

popd
