#!/bin/bash
# ~~~~~~~~~~~~~~
# compiling goby
# ~~~~~~~~~~~~~~
#
# satisfy the third party dependencies in DEPENDENCIES:
# > ./DEPENDENCIES
# run cmake to configure and generate Makefiles
# > ./CONFIGURE
# then, to install locally (goby/bin, goby/include, goby/lib
# > ./INSTALL
# to install to system
# > sudo ./INSTALL

if [ ! -e build/CMakeCache.txt ]; then
    ./CONFIGURE
fi

pushd build
if [[ $UID -ne 0 ]]; then
    # if user is not root, build to goby/bin, goby/include, and goby/lib:
    make $@
else
    # otherwise install to /usr/local/bin, /usr/local/lib, /usr/local/include
    make install $@
fi
popd
