#!/bin/bash

if [ -z "$1" ]; then
        echo "usage: analyze_dccl_xml file.xml"
        exit 0
fi

dccl_xml_to_dccl_proto $1 /tmp

file_with_path=${1%.xml}
file=${file_with_path##*/}

analyze_dccl /tmp/$file.proto
