#!/bin/bash

cd /home/toby/nightly/goby/1.0/build
make clean
rm -rf *
cmake .. -Dbuild_moos=ON -DCMAKE_BUILD_TYPE=Debug
ctest -D NightlyStart
ctest -D NightlyUpdate
ctest -D NightlyConfigure
ctest -D NightlyBuild
#ctest -D NightlyTest
#ctest -D NightlyMemCheck
#ctest -D NightlyCoverage
ctest -D NightlySubmit


cd /home/toby/nightly/goby/2.0/build
make clean
rm -rf *
cmake .. -DCMAKE_BUILD_TYPE=Debug -Dbuild_doc=ON
ctest -D NightlyStart
ctest -D NightlyUpdate
ctest -D NightlyConfigure
ctest -D NightlyBuild
ctest -D NightlyTest
ctest -D NightlyMemCheck
ctest -D NightlyCoverage
ctest -D NightlySubmit
